# frozen_string_literal: true

require 'auto12epl'

module Lab
  module LabellingService
    ##
    # Prints an order label for order with given accession number.
    class OrderLabel
      attr_reader :order

      def initialize(order_id)
        @order = Lab::LabOrder.find(order_id)
      end

      def print
        # NOTE: The arguments are passed into the method below not in the order
        #       the method expects (eg patient_id is passed to middle_name field)
        #       to retain compatibility with labels generated by the `lab test controller`
        #       application of the NLIMS suite.
        auto12epl.generate_epl(patient.given_name,
                               patient.family_name,
                               patient.nhid,
                               patient.birthdate.strftime('%d/%^b/%Y'),
                               '',
                               patient.gender,
                               '',
                               drawer,
                               '',
                               specimen,
                               reason_for_test,
                               order.accession_number,
                               order.accession_number)
      end

      def reason_for_test
        return 'Unknown' unless order.reason_for_test

        ConceptName.find_by_concept_id(order.reason_for_test.value_coded)&.name || 'Unknown'
      end

      def patient
        return @patient if @patient

        person = Person.find(order.patient_id)
        person_name = PersonName.find_by_person_id(order.patient_id)
        patient_identifier = PatientIdentifier.where(type: PatientIdentifierType.where(name: 'National id'),
                                                     patient_id: order.patient_id)
                                              .first

        @patient = OpenStruct.new(
          given_name: person_name.given_name,
          family_name: person_name.family_name,
          birthdate: person.birthdate,
          gender: person.gender,
          nhid: patient_identifier&.identifier || 'Unknown'
        )
      end

      def drawer
        return 'N/A' if order.concept_id == unknown_concept.concept_id

        name = PersonName.find_by_person_id(order.creator)
        return "#{name.given_name} #{name.family_name}" if name

        user = User.find(order.creator)
        user&.username || 'N/A'
      end

      def specimen
        return 'N/A' if order.concept_id == unknown_concept.concept_id

        ConceptName.find_by_concept_id(order.concept_id)&.name || 'Unknown'
      end

      def unknown_concept
        ConceptName.find_by_name('Unknown')
      end

      def auto12epl
        Auto12Epl.new
      end
    end
  end
end
